

--OXIMATA POU I TIMI TIS STILIS VRENTTIMES ANTISTOIXEI STIS KRATISEIS POU PRAGMATIKA EXOUN GINEI
SELECT VEH.VPLATENUMBER
FROM VEHICLE VEH
WHERE VEH.VRENTTIMES IN (SELECT COUNT(VPLATENUMBER) FROM RENTING WHERE VPLATENUMBER = VEH.VPLATENUMBER);

--KATIGORIES POU I TIMI TIS STILIS VEHICLECOUNT DEN ANTISTOIXEI STO PLITHOS TON OXIMATWN ME TA OPOIA SYSXETIZETAI ME TON PINAKA VEHICLECOUNT
SELECT VCAT.NAME
FROM VEHICLECAT VCAT
WHERE VCAT.VEHICLECOUNT NOT IN (SELECT COUNT(VPLATENUMBER) FROM VEHICLE WHERE VEHCATNAME = VCAT.NAME);

--KATIGORIES POU OLA TA OXIMATA EXOUN TO IDIO XRWMA KAI I TIMI TIS STILIS VEHICLECOUNT ANTISTOIXEI STO PLITHOS TON OXIMATON ME TA OPOIA SYSXETIZONTAI
SELECT VCAT.NAME
FROM VEHICLECAT VCAT
WHERE VCAT.VEHICLECOUNT IN (SELECT COUNT(VPLATENUMBER) FROM VEHICLE WHERE VEHCATNAME = VCAT.NAME)
        AND   VCAT.NAME IN (SELECT V.VEHCATNAME
                            FROM VEHICLE V
                            WHERE V.VCOLOR = ALL(SELECT VCOLOR FROM VEHICLE WHERE VEHCATNAME=V.VEHCATNAME)
                            );
        
        



