--3 PARADEIGMATA YPOANAZITISIS ME TELESTI IN

--EMFANIZEI TIS PINAKIDES TON AMAKSION POU TO PLITHOS TON ENIKIASEON EINAI ISO ME KAPIO APO TO PLITHOS TON OXIMATON KATHE KATIGORIAS
SELECT VPLATENUMBER 
FROM VEHICLE
WHERE VRENTTIMES IN (SELECT VEHICLECOUNT FROM VEHICLECAT);

--EMFANIZEI TA XROMATA TON OXIMATON POU NIKIASTIKAN TO 2021 KAI META
SELECT DISTINCT VCOLOR
FROM VEHICLE
WHERE VPLATENUMBER IN (SELECT VPLATENUMBER FROM RENTING WHERE OUTDATE >= TO_DATE('01/01/2021', 'DD/MM/YYYY'));

--EMFANIZEI TIS PINAKIDES TON OXIMATON POU DEN EXOUN EXTRAS
SELECT VPLATENUMBER 
FROM VEHICLE
WHERE VPLATENUMBER NOT IN (SELECT VPLATENUMBER FROM VEHICLE_EXTRAS);


--YPOANAZITISI ME SIGKRISI DYO STILWN

--OXIMATA ME ISO VCC KAI IPPODINAMI ME AFTO TOU HHH8888 
SELECT VPLATENUMBER 
FROM VEHICLE 
WHERE (VCC,VHORSEPOWER) IN (SELECT VCC,VHORSEPOWER FROM VEHICLE WHERE VPLATENUMBER = 'HHH8888');


--2 PARADEIGMATA YPOANAZITISIS ME SYNARTISI OMADOPOIISIS

--PIA OXIMATA(VPLATENUMBER) EXOUN LIGOTERI IPPODINAMI APO TO OXIMA POU EXEI TIN LIGOTERI IPPODINAMI KAI EINAI VEHCATNAME=CAR
SELECT VPLATENUMBER
FROM VEHICLE
WHERE VHORSEPOWER < (SELECT MIN(VHORSEPOWER) FROM VEHICLE WHERE VEHCATNAME ='CAR' )AND VEHCATNAME <> 'CAR';

--PIA OXIMATA(VPLATENUMBER) EXOUN MEGALITERO VCC APO TO OXIMA POU EXEI TO MEGALITERO VCC KAI EINAI VEHCATNAME=MOTORBIKE
SELECT VPLATENUMBER
FROM VEHICLE
WHERE VCC > (SELECT MIN(VCC) FROM VEHICLE WHERE VEHCATNAME ='MOTORBIKE' )AND VEHCATNAME <> 'MOTORBIKE';

--1 PARADIGMA YPOANAZITISIS ME ANY KAI 1 ME ALL

--EMFANIZEI TIS PINAKIDES OPION OXIMATON EXOUN LIGOTERI IPPODINAMI APO OPIODIPOTE KOSTOS KAPIOU EXTRA
SELECT VPLATENUMBER
FROM VEHICLE 
WHERE VHORSEPOWER < ANY(SELECT EPRICE FROM EXTRAS);

--EMFANIZEI TIS PINAKIDES OPION OXIMATON EXOUN MEGALITERI IPPODINAMI APO TA EPRICE OLON TON EXTRA
SELECT VPLATENUMBER
FROM VEHICLE 
WHERE VHORSEPOWER > ALL(SELECT EPRICE FROM EXTRAS);
