--WHERE ME ( =, >, <, < >, >=, <=,)
SELECT NAME,VEHICLECATEGORYPRICE
FROM VEHICLECAT
WHERE VEHICLECATEGORYPRICE<=50;

--SINTHETI WHERE ME AND.
SELECT VPLATENUMBER,VEHCATNAME,VCOLOR,VCC,VHORSEPOWER
FROM VEHICLE
WHERE VCOLOR='RED' AND VCC>1000;

--SINTHETI WHERE ME OR. 
SELECT VPLATENUMBER,VEHCATNAME,VCOLOR,VCC,VHORSEPOWER
FROM VEHICLE
WHERE VCOLOR='RED' OR VCOLOR='BLUE';

--SINTHETI WHERE ME NOT
SELECT VPLATENUMBER,VEHCATNAME,VCOLOR,VCC,VHORSEPOWER
FROM VEHICLE
WHERE NOT(VCOLOR='GREEN');

--WHERE ME NULL. 
SELECT CAFM,VPLATENUMBER,TO_CHAR(OUTDATE,'DD/MM/YYYY HH24:MI') AS OUTDATE,TO_CHAR(INDATE,'DD/MM/YYYY HH24:MI') AS INDATE
FROM RENTING
WHERE INDATE IS NULL;

--WHERE ME BETWEEN.
SELECT CAFM,VPLATENUMBER,TO_CHAR(OUTDATE,'DD/MM/YYYY HH24:MI') AS OUTDATE,TO_CHAR(INDATE,'DD/MM/YYYY HH24:MI') AS INDATE
FROM RENTING
WHERE INDATE BETWEEN TO_DATE('01/01/2020','DD/MM/YYYY') AND TO_DATE('01/01/2021','DD/MM/YYYY');

--WHERE ME IN. 
SELECT CAFM,VPLATENUMBER,TO_CHAR(OUTDATE,'DD/MM/YYYY HH24:MI') AS OUTDATE,TO_CHAR(INDATE,'DD/MM/YYYY HH24:MI') AS INDATE
FROM RENTING
WHERE VPLATENUMBER IN('AAA1111','BBB2222','DDD4444');

--2 WHERE ME LIKE. 
SELECT CFIRSTNAME,CLASTNAME
FROM CUSTOMER
WHERE CFIRSTNAME LIKE 'IW%';

SELECT CFIRSTNAME,CLASTNAME
FROM CUSTOMER
WHERE CLASTNAME LIKE '%OU';

--WHERE ME SIGKRISI 2 STILWN
SELECT CFIRSTNAME,CLASTNAME
FROM CUSTOMER
WHERE CFIRSTNAME >= CLASTNAME; -- sigkrinei alfavitika kai epidi epidi to O>I gia afto emfanizete mono o FILLIPOS FILIPPIDIS

--2 PARADIGMATA ME DISTINCT
SELECT DISTINCT CAFM,VPLATENUMBER
FROM RENTING;

SELECT DISTINCT VEHCATNAME
FROM VEHICLE;

--SELECT ME STILI IMEROMINIAS 
SELECT CAFM,VPLATENUMBER,TO_CHAR(OUTDATE,'DD/MM/YYYY HH24:MI') as OUTDATE
FROM RENTING
WHERE OUTDATE < TO_DATE('01/01/2021','DD/MM/YYYY');
