--FTHINOUSA ME MIA STILI
SELECT CLASTNAME,CFIRSTNAME,TO_CHAR(cRegDate,'DD/MM/YYYY') AS CREGDATE
FROM CUSTOMER
ORDER BY CREGDATE DESC;

--TAKSINOMISI ME 2 STILES
SELECT CLASTNAME,CFIRSTNAME,CAFM,CAT,TO_CHAR(cRegDate,'DD/MM/YYYY') AS CREGDATE
FROM CUSTOMER
ORDER BY CLASTNAME,CFIRSTNAME;

--TAKSINOMISI ME ARITHMO
SELECT CLASTNAME,CFIRSTNAME,TO_CHAR(cRegDate,'DD/MM/YYYY') AS CREGDATE
FROM CUSTOMER
ORDER BY 3;
